CREATE DATABASE IF NOT EXISTS playverseDB;
USE playverseDB;
CREATE TABLE IF NOT EXISTS `Economy_PurchaseBreakdownRaw` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RecordTimestamp` datetime NOT NULL,
  `UserData` varchar(255) DEFAULT NULL,
  `Category` varchar(255) DEFAULT NULL,
  `Type` int(11) DEFAULT NULL,
  `Cost` int(11) NOT NULL,
  `TotalBought` int(11) NOT NULL,
  `TotalCredits` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_RecordTimestamp` (`RecordTimestamp`),
  KEY `IDX_Cost` (`Cost`),
  KEY `IDX_RecordTimestampCost` (`RecordTimestamp`,`Cost`),
  KEY `IDX_TypeRecordTimestamp` (`Type`,`RecordTimestamp`),
  KEY `IDX_TypeCategory` (`Type`,`Category`),
  KEY `IDX_TypeCategoryRecordTimestamp` (`Type`,`Category`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=9664 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `EventLog` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EventType` int(11) NOT NULL,
  `Process` varchar(45) NOT NULL,
  `Message` longtext NOT NULL,
  `CallStack` longtext NOT NULL,
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `CreatedAt` (`CreatedAt`),
  KEY `TypeCreatedAt` (`EventType`,`CreatedAt`)
) ENGINE=InnoDB AUTO_INCREMENT=176027 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameAverageSessionLength` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `AverageSessionTypeLength_7` int(11) DEFAULT '0',
  `AverageSessionTypeLength_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1840212 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameMonitoringConfig` (
  `GameId` varchar(36) NOT NULL,
  `Title` varchar(128) NOT NULL,
  `ShortTitle` varchar(128) NOT NULL,
  `LaunchTime` timestamp NOT NULL,
  `ActiveUserSessionTypes` varchar(1024) NOT NULL,
  `ActiveUserDeltaThresholdPct_3Min` decimal(10,2) NOT NULL,
  `ActiveUserDeltaThresholdPct_6Min` decimal(10,2) NOT NULL,
  `PrivacyCompareSessionTypes` varchar(1024) NOT NULL,
  `MaxRunningHostingInstances` int(11) NOT NULL,
  `Notifications_Info` bit(1) NOT NULL,
  `Notifications_Warning` bit(1) NOT NULL,
  `Notifications_Error` bit(1) NOT NULL,
  `Notifications_PVSupport` bit(1) NOT NULL,
  `LastUpdateTime` timestamp NOT NULL,
  `LastUpdateUser` varchar(36) NOT NULL,
  PRIMARY KEY (`GameId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `GameMonitoringConfig` 
VALUES ('0-85ad9e444389413f929f8c95ffe9b324','Dungeon Defenders Eternity','DDE','2014-07-22 16:00:00','CoopHub,PrivateCoopHub,Campaign,Campaign6P,Challenge,Challenge8P',0.50,0.75,'CoopHub;PrivateCoopHub|Campaign;Campaign',100,'','','','\0','2014-09-05 23:31:50','jkight'),
('0-ea4f02fddd6f4abf85f04e3d873d5d24','Dungeon Defenders 2','DD2','2014-10-21 18:00:00','EntryHub,GroupHub,GroupHub_Private,SocialEntryHub',0.20,0.40,'EntryHub;EntryHub|GroupHub;GroupHub_Private',100,'','','','\0','2014-10-21 23:03:48','jkight');

CREATE TABLE IF NOT EXISTS `GameSessionMeta` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RecordCreated` datetime NOT NULL,
  `RecordLastUpdateTime` datetime NOT NULL,
  `GameSessionId` varchar(36) NOT NULL,
  `IP` varchar(15) NOT NULL,
  `Port` int(11) NOT NULL,
  `CreationTime` datetime NOT NULL,
  `SessionStarted` int(2) NOT NULL DEFAULT '0',
  `GameId` varchar(36) NOT NULL,
  `IsLocallyEmulated` int(2) NOT NULL,
  `LastUpdateTime` datetime NOT NULL,
  `Major` int(11) NOT NULL,
  `Minor` int(11) NOT NULL,
  `UsersCount` int(11) NOT NULL DEFAULT '0',
  `SessionTypeId` varchar(36) NOT NULL DEFAULT '0-01bc8646024443a7846f89628df09c06',
  `SessionTypeFriendly` varchar(255) DEFAULT NULL,
  `Status` int(11) NOT NULL DEFAULT '0',
  `CurrentRanking` int(11) NOT NULL DEFAULT '0',
  `IsPartySession` int(11) NOT NULL,
  `GameSessionRankRangeMin` int(11) NOT NULL DEFAULT '0',
  `GameSessionRankRangeMax` int(11) NOT NULL DEFAULT '0',
  `StartLaunchCountDownTime` datetime NOT NULL,
  `IsPrivateSession` int(11) NOT NULL DEFAULT '0',
  `InitiatorUserId` varchar(36) NOT NULL DEFAULT '0-00000000000000000000000000000000',
  `IsHosted` int(11) NOT NULL DEFAULT '0',
  `SessionMetadata` varchar(1024) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_GameIdMajorGameSessionId` (`GameId`,`Major`,`GameSessionId`),
  KEY `IDX_GameIdMajorSessionTypeId` (`GameId`,`Major`,`SessionTypeId`)
) ENGINE=InnoDB AUTO_INCREMENT=174495 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=2236333 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_12hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=2060 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_15min` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=65926 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_24hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1024 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_30min` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=32966 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_5min` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=197764 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_6hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=4114 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameSessionUserStats_hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `SessionType` varchar(45) NOT NULL,
  `MaxNumPlayers` int(11) NOT NULL,
  `AvgPlayers` decimal(10,2) NOT NULL,
  `Sessions` int(11) NOT NULL,
  `PrivateAvgPlayers` decimal(10,2) NOT NULL,
  `PrivateSessions` int(11) NOT NULL,
  `TotalAvgPlayers` decimal(10,2) NOT NULL,
  `TotalSessions` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdTimestamp` (`GameId`,`RecordTimestamp`),
  KEY `IDX_GameIdSessionTypeTimestamp` (`GameId`,`SessionType`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=16486 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=2513472 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_12hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=4110 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_15min` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=197061 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_24hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=2048 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_30min` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=131302 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_5min` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=460118 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_6hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=8213 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `GameUserActivity_hour` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `RegionName` varchar(45) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `GameSessionUsers` int(11) DEFAULT '0',
  `EventListeners` int(11) DEFAULT '0',
  `TitleScreenUsers` int(11) DEFAULT '0',
  `SessionTypeName_0` varchar(45) DEFAULT '',
  `SessionTypeUsers_0` int(11) DEFAULT '0',
  `SessionTypeName_1` varchar(45) DEFAULT '',
  `SessionTypeUsers_1` int(11) DEFAULT '0',
  `SessionTypeName_2` varchar(45) DEFAULT '',
  `SessionTypeUsers_2` int(11) DEFAULT '0',
  `SessionTypeName_3` varchar(45) DEFAULT '',
  `SessionTypeUsers_3` int(11) DEFAULT '0',
  `SessionTypeName_4` varchar(45) DEFAULT '',
  `SessionTypeUsers_4` int(11) DEFAULT '0',
  `SessionTypeName_5` varchar(45) DEFAULT '',
  `SessionTypeUsers_5` int(11) DEFAULT '0',
  `SessionTypeName_6` varchar(45) DEFAULT '',
  `SessionTypeUsers_6` int(11) DEFAULT '0',
  `SessionTypeName_7` varchar(45) DEFAULT '',
  `SessionTypeUsers_7` int(11) DEFAULT '0',
  `SessionTypeUsers_Other` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdRegionNameTimestamp` (`GameId`,`RegionName`,`RecordTimestamp`),
  KEY `IDX_RegionNameTimestamp` (`RegionName`,`RecordTimestamp`),
  KEY `IDX_Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=65655 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `HostingInstance_ComputeRaw` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RecordTimestamp` datetime NOT NULL,
  `HostingInstance_Id` varchar(36) NOT NULL,
  `HostingInstance_MachineId` varchar(45) NOT NULL,
  `HostingInstance_IP` varchar(15) NOT NULL,
  `HostingInstance_CreationTime` datetime NOT NULL,
  `HostingInstance_StartTime` datetime NOT NULL,
  `HostingInstance_LastUpdateTime` datetime NOT NULL,
  `HostingInstance_GameId` varchar(36) NOT NULL,
  `RegionHostingConfiguration_Id` varchar(36) NOT NULL,
  `RegionHostingConfiguration_MinimumNumInstances` int(11) NOT NULL,
  `RegionHostingConfiguration_MaximumFreeInstances` int(11) NOT NULL,
  `HostingConfiguration_Name` varchar(45) NOT NULL DEFAULT 'Unnamed',
  `HostingRegion_Name` varchar(45) NOT NULL,
  `GameVersion_Id` varchar(36) NOT NULL,
  `GameVersion_Major` int(11) DEFAULT NULL,
  `GameVersion_Minor` int(11) DEFAULT NULL,
  `GameVersion_Status` int(11) DEFAULT NULL,
  `GameVersion_Label` int(11) DEFAULT NULL,
  `HostingInstance_Status` int(11) NOT NULL,
  `HostingInstance_Health` int(11) NOT NULL,
  `HostingInstance_MaximumComputeUnits` int(11) NOT NULL DEFAULT '10',
  `HostingInstance_TotalComputeUnits` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_CalcTotalComputeUnits` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_ServersCount` int(11) NOT NULL,
  `HostingInstance_CalcServersCount` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_AvgComputeUnitsAcrossServers` decimal(35,2) NOT NULL DEFAULT '0.00',
  `HostingInstance_MaxUserCount` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_UserCount` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdHostingInstance` (`HostingInstance_GameId`,`HostingInstance_Id`),
  KEY `IDX_GameIdCreationTimeHostingInstanceIdUpdateTime` (`HostingInstance_GameId`,`HostingInstance_CreationTime`,`HostingInstance_Id`,`HostingInstance_LastUpdateTime`)
) ENGINE=InnoDB AUTO_INCREMENT=3945930 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `HostingInstanceMeta` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RecordTimestamp` datetime NOT NULL,
  `HostingInstance_Id` varchar(36) NOT NULL,
  `HostingInstance_MachineId` varchar(45) NOT NULL,
  `HostingInstance_IP` varchar(15) NOT NULL,
  `HostingInstance_CreationTime` datetime NOT NULL,
  `HostingInstance_StartTime` datetime NOT NULL,
  `HostingInstance_LastUpdateTime` datetime NOT NULL,
  `HostingInstance_GameId` varchar(36) NOT NULL,
  `RegionHostingConfiguration_Id` varchar(36) NOT NULL,
  `RegionHostingConfiguration_MinimumNumInstances` int(11) NOT NULL,
  `RegionHostingConfiguration_MaximumFreeInstances` int(11) NOT NULL,
  `HostingConfiguration_Name` varchar(45) NOT NULL DEFAULT 'Unnamed',
  `HostingRegion_Name` varchar(45) NOT NULL,
  `GameVersion_Id` varchar(36) NOT NULL,
  `GameVersion_Major` int(11) DEFAULT NULL,
  `GameVersion_Minor` int(11) DEFAULT NULL,
  `GameVersion_Status` int(11) DEFAULT NULL,
  `GameVersion_Label` int(11) DEFAULT NULL,
  `HostingInstance_Status` int(11) NOT NULL,
  `HostingInstance_Health` int(11) NOT NULL,
  `HostingInstance_MaximumComputeUnits` int(11) NOT NULL DEFAULT '10',
  `HostingInstance_TotalComputeUnits` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_CalcTotalComputeUnits` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_ServersCount` int(11) NOT NULL,
  `HostingInstance_CalcServersCount` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_AvgComputeUnitsAcrossServers` decimal(35,2) NOT NULL DEFAULT '0.00',
  `HostingInstance_MaxUserCount` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_UserCount` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdHostingInstance` (`HostingInstance_GameId`,`HostingInstance_Id`),
  KEY `IDX_GameIdCreationTimeHostingInstanceIdUpdateTime` (`HostingInstance_GameId`,`HostingInstance_CreationTime`,`HostingInstance_Id`,`HostingInstance_LastUpdateTime`)
) ENGINE=InnoDB AUTO_INCREMENT=2987266 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hostinginstancemeta` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RecordTimestamp` datetime NOT NULL,
  `HostingInstance_Id` varchar(36) NOT NULL,
  `HostingInstance_MachineId` varchar(45) NOT NULL,
  `HostingInstance_IP` varchar(15) NOT NULL,
  `HostingInstance_CreationTime` datetime NOT NULL,
  `HostingInstance_StartTime` datetime NOT NULL,
  `HostingInstance_LastUpdateTime` datetime NOT NULL,
  `HostingInstance_GameId` varchar(36) NOT NULL,
  `RegionHostingConfiguration_Id` varchar(36) NOT NULL,
  `RegionHostingConfiguration_MinimumNumInstances` int(11) NOT NULL,
  `RegionHostingConfiguration_MaximumFreeInstances` int(11) NOT NULL,
  `HostingConfiguration_Name` varchar(45) NOT NULL DEFAULT 'Unnamed',
  `HostingRegion_Name` varchar(45) NOT NULL,
  `GameVersion_Id` varchar(36) NOT NULL,
  `GameVersion_Major` int(11) DEFAULT NULL,
  `GameVersion_Minor` int(11) DEFAULT NULL,
  `GameVersion_Status` int(11) DEFAULT NULL,
  `GameVersion_Label` int(11) DEFAULT NULL,
  `HostingInstance_Status` int(11) NOT NULL,
  `HostingInstance_Health` int(11) NOT NULL,
  `HostingInstance_MaximumComputeUnits` int(11) NOT NULL DEFAULT '10',
  `HostingInstance_TotalComputeUnits` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_CalcTotalComputeUnits` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_ServersCount` int(11) NOT NULL,
  `HostingInstance_CalcServersCount` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_AvgComputeUnitsAcrossServers` decimal(35,2) NOT NULL DEFAULT '0.00',
  `HostingInstance_MaxUserCount` int(11) NOT NULL DEFAULT '0',
  `HostingInstance_UserCount` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_GameIdHostingInstance` (`HostingInstance_GameId`,`HostingInstance_Id`),
  KEY `IDX_GameIdCreationTimeHostingInstanceIdUpdateTime` (`HostingInstance_GameId`,`HostingInstance_CreationTime`,`HostingInstance_Id`,`HostingInstance_LastUpdateTime`)
) ENGINE=InnoDB AUTO_INCREMENT=2888042 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `MonitoringStats` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GameId` varchar(36) NOT NULL,
  `Type` varchar(50) NOT NULL,
  `Count` int(11) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `GameIdTypeTimestamp` (`GameId`,`Type`,`RecordTimestamp`),
  KEY `TypeTimestamp` (`Type`,`RecordTimestamp`),
  KEY `Timestamp` (`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=1010 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Retention_DailyCounts` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `NewUserTotal` int(36) NOT NULL,
  `TotalLogins` int(36) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_Date` (`Date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `Retention_FirstLogin` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UserId` varchar(36) NOT NULL,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UserId` (`UserId`),
  KEY `IDX_UserIdTimestamp` (`UserId`,`RecordTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=62243 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Retention_Login` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UserId` varchar(36) NOT NULL,
  `LoginTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `RecordDate` date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uniqueUserIdOnDay` (`RecordDate`,`UserId`),
  KEY `IDX_RecordTimeStampUserId` (`LoginTimestamp`,`UserId`)
) ENGINE=InnoDB AUTO_INCREMENT=702742 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Retention_ReturnersView` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RecordTimestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `NewReturns` decimal(10,0) DEFAULT NULL,
  `ContinuingReturns` decimal(10,0) DEFAULT NULL,
  `ReactivatedReturns` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `RecordTimestamp` (`RecordTimestamp`),
  KEY `IDX_RecordTimestamp` (`RecordTimestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `Retention_TwoWeekView` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `NewUsers` int(11) NOT NULL DEFAULT '0',
  `Day1` float NOT NULL DEFAULT '0',
  `Day2` float NOT NULL DEFAULT '0',
  `Day3` float NOT NULL DEFAULT '0',
  `Day4` float NOT NULL DEFAULT '0',
  `Day5` float NOT NULL DEFAULT '0',
  `Day6` float NOT NULL DEFAULT '0',
  `Day7` float NOT NULL DEFAULT '0',
  `Day8` float NOT NULL DEFAULT '0',
  `Day9` float NOT NULL DEFAULT '0',
  `Day10` float NOT NULL DEFAULT '0',
  `Day11` float NOT NULL DEFAULT '0',
  `Day12` float NOT NULL DEFAULT '0',
  `Day13` float NOT NULL DEFAULT '0',
  `Day14` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Date` (`Date`),
  KEY `IDX_Date` (`Date`)
) ENGINE=InnoDB AUTO_INCREMENT=133 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `UserSessionMeta` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UserId` varchar(36) DEFAULT NULL,
  `GameId` varchar(36) DEFAULT NULL,
  `UserSessionId` varchar(36) DEFAULT NULL,
  `Platform` varchar(255) DEFAULT NULL,
  `LoginTimestamp` datetime DEFAULT CURRENT_TIMESTAMP,
  `LogoffTimestamp` datetime DEFAULT NULL,
  `SessionLength` bigint(20) DEFAULT NULL,
  `InstallDateRecord` int(1) DEFAULT '0',
  `RetentionCohortType` int(1) DEFAULT '-1',
  `RecordDate` date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UserSessionId` (`UserSessionId`),
  KEY `IDX_RecordTimeStampUserId` (`LoginTimestamp`,`UserId`),
  KEY `IDX_RecordTimeStampUserSessionId` (`LoginTimestamp`,`UserSessionId`),
  KEY `IDX_RecordTimeStampGameIdUserSessionId` (`LoginTimestamp`,`GameId`,`UserSessionId`),
  KEY `IDX_RecordTimeStampGameId` (`LoginTimestamp`,`GameId`),
  KEY `IDX_RecordTimeStampRetentionCohortType` (`LoginTimestamp`,`RetentionCohortType`)
) ENGINE=InnoDB AUTO_INCREMENT=1444521 DEFAULT CHARSET=utf8;
